# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
image:
  - Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python310"

build: false

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install -r dev-requirements.txt"
  - "%PYTHON%\\python.exe -m pip install -e ."

test_script:
  - "%PYTHON%\\python.exe -c \"import sys; print(f'sys.platform={sys.platform}')\""
  - "%PYTHON%\\python.exe -c \"import distutils.util; print(f'distutils.util.get_platform()={distutils.util.get_platform()}')\""
  - "%PYTHON%\\python.exe -m pytest --cov-report term-missing --cov wagon tests -v"
